name: Create JIRA issue

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - uses: atlassian/gajira-create@v3
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          summary: '[${{ github.repository }}] ${{ github.event.issue.title }}'
          description: ${{ github.event.issue.html_url }}
          # fields: '{"customfield_10171": "test"}' # TODO what is this for?
