name: Create JIRA issue

on:
  issues:
    types: [labeled]

jobs:
  create-jira-issue:
    if: github.event.label.name == 'JIRA'
    runs-on: ubuntu-latest
    steps:
      - name: Login to JIRA
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create JIRA issue
        id: create_jira_issue
        uses: atlassian/gajira-create@v3
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          summary: '[${{ github.repository }}#${{ github.event.issue.number }}] ${{ github.event.issue.title }}'
          description: ${{ github.event.issue.html_url }}

      - name: Add JIRA issue key to GitHub issue body
        uses: actions-cool/issues-helper@v3
        with:
          actions: update-issue
          body: "<!-- This line was added by GitHub Actions. Do not remove! -->\n\
            ${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create_jira_issue.outputs.issue }}\n\n\
            ${{ github.event.issue.body }}"
