name: Create JIRA issue if labeled

on:
  issues:
    types: [labeled]

jobs:
  create-jira-issue:
    if: contains(github.event.issue.labels.*.name, 'Create JIRA issue')
    runs-on: ubuntu-latest
    steps:
      - name: Login to JIRA
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create JIRA issue
        id: create_jira_issue
        uses: atlassian/gajira-create@v3
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          summary: '[${{ github.repository }}#${{ github.event.issue.number }}] ${{ github.event.issue.title }}'
          description: ${{ github.event.issue.html_url }}

      - uses: actions/checkout@v2

      # Remove old label to prevent this job from running whenever the issue is labeled.
      - name: Remove old label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Create JIRA issue
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Add new label so that users can easily identify which GitHub issues have corresponding JIRA issues.
      - name: Add new label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: JIRA
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment JIRA issue URL
        uses: actions-ecosystem/action-create-comment@v1
        with:
          body: ${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create_jira_issue.outputs.issue }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
